#lang racket

(define cartagoGraph '((a((f 2)))
                       (b((a 10) (c 5)))
                       (c((b 5) (d 7)))
                       (d((c 7)))
                       (e((d 3)))
                       (f((g 5)))
                       (g((h 1) (l 8)))
                       (h((g 1) (i 10)))
                       (i((j 1)))
                       (j((e 4) (o 8)))
                       (k((p 4)))
                       (l((k 6) (m 7)))
                       (m((l 7)))
                       (n((i 6) (m 2) (s 5)))
                       (o((j 8) (t 10)))
                       (p((q 2)))
                       (q((l 3) (r 9)))
                       (r((s 7)))
                       (s((n 5)))
                       (t((s 9)))))

(define herediaGraph '((a((f 4)))
                       (b((a 8) (c 9) (g 5)))
                       (c((b 9) (d 7)))
                       (d((c 7) (i 7)))
                       (e((d 2) (j 1)))
                       (f((a 4) (g 4)))
                       (g((h 3) (l 2)))
                       (h((g 3) (c 6) (i 8)))
                       (i((h 8) (j 10) (n 9)))
                       (j((e 1) (o 3)))
                       (k((l 1)))
                       (l((g 2) (k 1)))
                       (m((l 10) (n 6)))
                       (n((m 6)))
                       (o((j 3) (n 5)))))

(define alajuelaGraph '((a((b 4)))
                       (b((c 6) (g 9)))
                       (c((d 1) (h 8)))
                       (d((c 1) (e 5)))
                       (e((d 5) (j 3)))
                       (f((a 2) (g 9)))
                       (g((b 9) (f 9) (h 2)))
                       (h((i 1)))
                       (i((d 10)))
                       (j((i 7)))))